apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-app
  labels:
    app: qr-code-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-code-app
  template:
    metadata:
      labels:
        app: qr-code-app
    spec:
      containers:
        - name: qr-code-app
          image: your-dockerhub-username/qr-code-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
