apiVersion: v1
kind: Service
metadata:
  name: nodejs-k8s-demo-service
spec:
  type: NodePort
  selector:
    app: nodejs-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
