name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old local image if exists
        run: |
          docker image rm -f ${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-demo:latest || true
          docker system prune -af --volumes || true

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-demo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-demo:latest


